#! /bin/bash

PATH=/usr/bin:/bin
DATE=$(date +%Y%m%d%H%M%S%N)
EXCLUDE=/home/daniel/code/.exclude.txt
TARGETDIR=/var/backups/code/

cd /home/daniel
mkdir -p $TARGETDIR
: >$EXCLUDE
for d in "venv" ".venv" ".git"; do
  find code -type d -iname $d >>$EXCLUDE
done

sudo tar -C /home/daniel -X $EXCLUDE -czf $TARGETDIR/code_$DATE.tar.gz code
