#! /bin/bash

old="$1"
new="$2"
myacc=Danielzapirtan

cd $HOME/code/myacc
rm -rf $old $new
gh repo create $new --public
git clone https://github.com/$myacc/$old.git
cp -a $old $new
cd $new
git remote set-url origin https://github.com/$myacc/$new.git
git push -u origin main

